title: Digital Health Humanities Toolkit
affiliation:
sass:
  style: compressed

baseurl: /toolkit

collections:
  lessons:
    output: true
  about:
    output: true

# --------------------------------------------------------------
# SITE MENU SETTINGS
# --------------------------------------------------------------
# Each menu item needs a `label` (whats shown), and a `link`
# (where it goes). An item can optionally have a dropdown
# submenu via `sub`.

menu:
  - label: 'About'
    link: '#'
  - label: 'Lessons'
    sub:
      - label: 'All Lessons'
        link: 'lessons/'
      - label: 'Digital Basics'
        link: 'lessons/databasics'
      - label: 'Project Management'
        link: 'lessons/ProjectManagement'
      - label: 'Data Ethics'
        link: 'lessons/dataethics'
  - label: 'White Paper'
    link: '#'
  - label: 'Resources'
    link: '#'

# --------------------------------------------------------------
# SITE FOOTER SETTINGS
# --------------------------------------------------------------
#

footer:
  links:
    - label: 'UCSF'
    - label: 'GitHub'

    
exclude :
    - Gemfile
    - Gemfile.lock
    - CNAME
    - LICENSE
    - README.md
    - INSTALL.md
    - vendor/bundle
    - vendor/cache
    