title: Digital Health Humanities Toolkit
description: "Note: The Digital Health Humanities Toolkit is currently a Work in Progress. The full site will be released later in 2026."
affiliation:
remote_theme: DigitalHealthHumanities/toolkittheme
sass:
  style: compressed

url: https://digitalhealthhumanities.github.io
baseurl: /toolkit

plugins:
  - jekyll-remote-theme

collections:
  lessons:
    output: true
  papers:
    output: true

# --------------------------------------------------------------
# SITE MENU SETTINGS
# --------------------------------------------------------------
# Each menu item needs a `label` (whats shown), and a `link`
# (where it goes). An item can optionally have a dropdown
# submenu via `sub`.

menu:
  - label: 'About'
    link: 'about/'
  - label: 'Lessons'
    sub:
      - label: 'All Lessons'
        link: 'lessons/'
      - label: 'Digital Basics'
        link: 'lessons/databasics'
      - label: 'Project Management'
        link: 'lessons/ProjectManagement'
      - label: 'Data Ethics'
        link: 'lessons/dataethics'
  - label: 'White Paper'
    link: '/white-paper'
  - label: 'Resources'
    link: '#'

# --------------------------------------------------------------
# SITE FOOTER SETTINGS
# --------------------------------------------------------------
#

footer:
  links:
    - label: 'UCSF'
    - label: 'GitHub'

    
exclude :
    - Gemfile
    - Gemfile.lock
    - CNAME
    - LICENSE
    - README.md
    - INSTALL.md
    - vendor/bundle
    - vendor/cache
    - vendor/ruby
