title:
affiliation:

baseurl: /toolkit

collections:
  lessons:
    output: true
  about:
    output: true
    
exclude :
    - Gemfile
    - Gemfile.lock
    - CNAME
    - LICENSE
    - README.md
    - INSTALL.md
    - vendor/bundle
    